name: Data Warehouse Quality Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-pipeline:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "CiTestPassword123!"
        ports:
          - 1433:1433
        options: >-
          --health-cmd="/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P CiTestPassword123! -C -Q 'SELECT 1' || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install sqlcmd
        run: |
          curl -sSL https://github.com/microsoft/go-sqlcmd/releases/download/v1.10.0/sqlcmd-linux-amd64.tar.bz2 -o sqlcmd.tar.bz2
          tar -xjf sqlcmd.tar.bz2
          chmod +x ./sqlcmd
          sudo mv ./sqlcmd /usr/local/bin/sqlcmd
          echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Create database and schemas
        run: |
          sqlcmd -S localhost -U sa -P "CiTestPassword123!" -C -i scripts/init_database.sql -b

      - name: Deploy DDL (create bronze tables)
        run: |
          sqlcmd -S localhost -U sa -P "CiTestPassword123!" -C -d DataWarehouse -i scripts/bronze/ddl_bronze.sql -b

      - name: Deploy DDL (create silver tables)
        run: |
          sqlcmd -S localhost -U sa -P "CiTestPassword123!" -C -d DataWarehouse -i scripts/silver/ddl_silver.sql -b

      - name: Deploy stored procedures (bronze & silver)
        run: |
          sqlcmd -S localhost -U sa -P "CiTestPassword123!" -C -d DataWarehouse -i scripts/bronze/proc_load_bronze.sql -b
          sqlcmd -S localhost -U sa -P "CiTestPassword123!" -C -d DataWarehouse -i scripts/silver/proc_load_silver.sql -b

      - name: Run load_bronze
        run: |
          sqlcmd -S localhost -U sa -P "CiTestPassword123!" -C -d DataWarehouse -Q "EXEC bronze.load_bronze @source_path = '$(pwd)/datasets';"

      - name: Run load_silver
        run: |
          sqlcmd -S localhost -U sa -P "CiTestPassword123!" -C -d DataWarehouse -Q "EXEC silver.load_silver;"

      - name: Deploy gold views
        run: |
          sqlcmd -S localhost -U sa -P "CiTestPassword123!" -C -d DataWarehouse -i scripts/gold/ddl_gold.sql -b

      - name: Run quality checks
        run: |
          sqlcmd -S localhost -U sa -P "CiTestPassword123!" -C -d DataWarehouse -i tests/quality_checks.sql -b
